name: Build, test and publish docker image

on:
  push:
    branches:
      - "**"

env:
  JAVA_DISTRIBUTION: adopt
  JAVA_VERSION: 17
  DOCKER_IMAGE_NAME: massicer/friend-bar
  REPOSITORY_URI: cr.tools.int.casavo.tech/sellers/snake

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{env.JAVA_DISTRIBUTION}}
          java-version: ${{env.JAVA_VERSION}}

      - name: Run Tests
        run: make test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: ${{env.JAVA_DISTRIBUTION}}
          java-version: ${{env.JAVA_VERSION}}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Assemble Artifacts
        run: ./gradlew build

      - name: Build Docker Image
        run: docker build -f src/main/docker/Dockerfile.jvm -t ${{env.DOCKER_IMAGE_NAME}}:${{github.sha}} .

      - name: Login to Docker Hub
#        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image
#        if: ${{ github.ref == 'refs/heads/main' }}
        run:
          docker push ${{env.LOCAL_IMAGE_NAME}}:${{github.sha}}